channel_sources:
  - tudat-team, conda-forge, defaults
channel_targets:
  - tudat-team main
boost_cpp:
  - 1.64.0
  - 1.65.0
  - 1.66.0
  - 1.67.0
  - 1.68.0
  - 1.69.0
c_compiler_version:   # [macOS]
  - '9'               # [macOS]
cxx_compiler_version: # [macOS]
  - '9'               # [macOS]