channel_sources:
  - tudat-team, conda-forge, defaults
channel_targets:
  - tudat-team main
boost_cpp:
  - 1.72.0
c_compiler_version:            # [osx] 
  - 14                         # [osx]
cxx_compiler_version:          # [osx] 
  - 14                         # [osx]
