channel_sources:
  - tudat-team, conda-forge, defaults         # [not win]
  - m2sys, tudat-team, conda-forge, defaults  # [win]
channel_targets:
  - tudat-team main
boost_cpp:
  - 1.67.0
tudat_resources:
  - 1.1.2
