channel_sources:
  - tudat-team, conda-forge, defaults   # [not win]
  - tudat-team, conda-forge, rdonnelly, defaults   # [win]
channel_targets:
  - tudat-team main
boost_cpp:
  - 1.69.0
  - 1.70.0
  - 1.71.0
  - 1.72.0
