channel_sources:
  - tudat-team/label/dev, tudat-team, conda-forge, defaults
channel_targets:
  - tudat-team dev
c_compiler_version:            # [osx] 
  - 14                         # [osx]
cxx_compiler_version:          # [osx] 
  - 14                         # [osx]
c_compiler:                    # [win] 
  - vs2017                      # [win]
cxx_compiler:                  # [win] 
  - vs2017                      # [win]
