channel_sources:
  - tudat-team/label/dev, tudat-team, conda-forge, defaults
channel_targets:
  - tudat-team dev
boost_cpp:
  - 1.72.0
c_compiler_version:            # [osx] 
  - 14                         # [osx]
cxx_compiler_version:          # [osx] 
  - 14                         # [osx]
