package:
#  name:  {{ environ.get('CIRCLE_PROJECT_REPONAME', 'tudat') }}
  name:  tudat
  version: 2.8.19
#  version: {{ environ.get('NEW_GIT_TAG', 'dev') }}

source:
  git_url: https://github.com/tudat-team/tudat.git
  git_rev: 88bcc2e94a8b41ce3fa36b04e61cd48b04711c8e

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    - cspice-cmake
    - sofa-cmake
  detect_binary_files_with_prefix: true
  missing_dso_whitelist:
    - libgcc-ng
    - libstdcxx-ng
    - libm
    - libc


requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - vs2017_{{ target_platform  }}    # [win]
    - cmake
    - eigen

outputs:
  - name: {{ environ.get('CIRCLE_PROJECT_REPONAME', 'tudat') }}
    requirements:
      build:
        # Tools required to build the package. These packages are run on the build
        # system and include things such as revision control systems (Git, SVN) make
        # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
        # or native when not cross-compiling), and any source pre-processors.
        - boost-cpp==1.64.0
        - cspice-cmake
        - sofa-cmake
        - eigen

      host:
        # Packages that need to be specific to the target platform when the
        # target platform is not necessarily the same as the native build
        # platform
        - boost-cpp==1.64.0
        - cspice-cmake
        - sofa-cmake
        - eigen

      run:
        # Packages required to run the package. These are the dependencies
        # that are installed automatically whenever the package is installed.
        # Package names should follow the package match specifications.
        - {{ pin_compatible('boost-cpp', max_pin='x.x') }}

about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: Tudat Bundle packs Tudat and external libraries in a modular fashion
