github:
  user_or_org: tudat-team

conda_forge_output_validation: true

provider:
  linux: azure
  osx: azure
  win: azure
  linux_ppc64le: None
  linux_aarch64: None

build_platform:
  osx_arm64: osx_64
test_on_native_only: true

appveyor:
  secure:
    BINSTAR_TOKEN: vWktDJSW9Rh2frmNkzdUHF2n4WzalOoKudWGdBLo6jcC/suzU+fViO/3/TxLOnmW

azure:
  # toggle for storing the conda build_artifacts directory (including the
  # built packages) as an Azure pipeline artifact that can be downloaded
  store_build_artifacts: False
  variables:
    - group: "conda-smithy"
